site_name: AdminerEvo
site_description: AdminerEvo documentation
docs_dir: docs/
nav:
  - Home: index.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.annotate
repo_url: https://github.com/adminerevo/adminerevo
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/adminerevo/adminerevo
